import type { Metadata } from "next";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";

const fontNormal = localFont({
  src: "../assets/fonts/normal.woff2",
});

const fontMono = localFont({
  src: "../assets/fonts/mono.woff2",
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Next.js by Trishan - The React Framework",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(fontNormal.className, fontMono.variable)}>
        {children}
      </body>
    </html>
  );
}
